# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy.

To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook.

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
from google.colab import files
uploaded = files.upload()
applicant_data_df = pd.read_csv("applicants_data.csv")

                                # YOUR CODE HERE

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df

Saving applicants_data.csv to applicants_data.csv

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Review the data types associated with the columns
# YOUR CODE HERE
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
applicant_data_df.columns

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(['EIN', 'NAME'], axis=1)
# YOUR CODE HERE

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables
categorical_variables = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']
# YOUR CODE HERE

# Display the categorical variables list
# YOUR CODE HERE
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'STATUS',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False, drop='first')
# YOUR CODE HERE

In [8]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']])
# YOUR CODE HERE
len(encoded_data[0])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

108

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data,columns=enc.get_feature_names_out(categorical_variables))
# YOUR CODE HERE

# Review the DataFrame
# YOUR CODE HERE
encoded_df

,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,APPLICATION_TYPE_T3,...,STATUS_1,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df_main = pd.concat([applicant_data_df[["STATUS","ASK_AMT","IS_SUCCESSFUL"]], encoded_df], axis=1)
# YOUR CODE HERE

# Review the Dataframe
# YOUR CODE HERE
encoded_df_main

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,STATUS_1,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [11]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df_main['IS_SUCCESSFUL']
# YOUR CODE HERE

# Display a sample of y
# YOUR CODE HERE
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [12]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df_main.drop(columns=['IS_SUCCESSFUL'])
# YOUR CODE HERE

# Review the features DataFrame
# YOUR CODE HERE
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,...,STATUS_1,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34295,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34296,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34297,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34298,1,36500179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [13]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)# YOUR CODE HERE

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()
# YOUR CODE HERE

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)
# YOUR CODE HERE

# Fit the scaler to the features training dataset
X_train_scaled = scaler.transform(X_train)
# YOUR CODE HERE
X_test_scaled = scaler.transform(X_test)
# YOUR CODE HERE

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [15]:
# Define the the number of inputs (features) to the model
number_input_features = X.shape[1]
# YOUR CODE HERE

# Review the number of features
number_input_features

110

In [16]:
# Define the number of neurons in the output layer
number_output_neurons = 2
# YOUR CODE HERE

In [17]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  10
# YOUR CODE HERE

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

10

In [18]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  5
# YOUR CODE HERE

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

5

In [19]:
# Create the Sequential model instance
nn = Sequential()
# YOUR CODE HERE

In [20]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))
# YOUR CODE HERE

In [21]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))
# YOUR CODE HERE

In [22]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(1, activation="sigmoid"))
# YOUR CODE HERE

In [23]:
# Display the Sequential model summary
nn.summary()
# YOUR CODE HERE

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                1110

 dense_1 (Dense)             (None, 5)                 55

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 1171 (4.57 KB)
Trainable params: 1171 (4.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [24]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
# YOUR CODE HERE

In [25]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50)
# YOUR CODE HERE

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6172 - accuracy: 0.6770
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7214
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5574 - accuracy: 0.7252
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5539 - accuracy: 0.7293
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7303
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7317
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7322
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7312
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7323
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7327
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7337
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7338
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7342
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7324
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7325
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7331
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7339
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7337
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7336
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7339
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7335
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7343
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7350
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7348
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7354
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7343
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7357
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7354
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7364
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7355
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7351
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7357
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7362
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7362
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7360
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7359
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7363
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7352
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7353
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7371
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7365
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7357
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7372
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7358
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7365
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7364
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7367
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7373

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [26]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5562 - accuracy: 0.7314 - 813ms/epoch - 3ms/step
Loss: 0.5561932325363159, Accuracy: 0.7314285635948181

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [27]:
# Set the model's file path
# YOUR CODE HERE


file_path = "/Users/matt/Desktop/BootCamp/Starter_Code_13/Resources/AlphabetSoup.H5"




# Export your model to a HDF5 file
# YOUR CODE HERE
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [28]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])


# Review the number of features
number_input_features

110

In [29]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 4
# YOUR CODE HERE

In [30]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 12
# YOUR CODE HERE

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

12

In [31]:
# Create the Sequential model instance
nn_A1 = Sequential()
# YOUR CODE HERE

In [32]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))
# YOUR CODE HERE


# Output layer
nn_A1.add(Dense(1, activation="sigmoid"))
# YOUR CODE HERE


# Check the structure of the model
# YOUR CODE HERE
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 12)                1332

 dense_4 (Dense)             (None, 1)                 13

=================================================================
Total params: 1345 (5.25 KB)
Trainable params: 1345 (5.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [33]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
# YOUR CODE HERE

In [34]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)
# YOUR CODE HERE

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.6074 - accuracy: 0.7040
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5677 - accuracy: 0.7257
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5597 - accuracy: 0.7284
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7280
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7297
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5533 - accuracy: 0.7294
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5516 - accuracy: 0.7297
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7301
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7311
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7308
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7317
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7328
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7318
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7329
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7326
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7322
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7337
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7329
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7332
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7329
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7337
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7335
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7332
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7335
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7350
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7333
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7339
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7344
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7334
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7345
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7350
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7339
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7347
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7348
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7342
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7352
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7344
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7356
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7348
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7359
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7345
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7352
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7356
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7354
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7348
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5425 - accuracy: 0.7362
Epoch 47/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7363
Epoch 48/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5420 - accuracy: 0.7360
Epoch 49/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5421 - accuracy: 0.7361
Epoch 50/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5420 - accuracy: 0.7346

#### Alternative Model 2

In [35]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

110

In [36]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 4
# YOUR CODE HERE

In [37]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 16
# YOUR CODE HERE

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

16

In [38]:
# Create the Sequential model instance
nn_A2 = Sequential()
# YOUR CODE HERE

In [39]:
# First hidden layer
# YOUR CODE HERE
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))


# Output layer
# YOUR CODE HERE
nn_A2.add(Dense(1, activation="sigmoid"))

# Check the structure of the model
# YOUR CODE HERE
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 16)                1776

 dense_6 (Dense)             (None, 1)                 17

=================================================================
Total params: 1793 (7.00 KB)
Trainable params: 1793 (7.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
# Compile the model
# YOUR CODE HERE
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
# Fit the model
# YOUR CODE HERE
model = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 6s 5ms/step - loss: 0.6139 - accuracy: 0.6937
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5666 - accuracy: 0.7254
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5590 - accuracy: 0.7270
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5548 - accuracy: 0.7282
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5527 - accuracy: 0.7283
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5518 - accuracy: 0.7293
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7301
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7299
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7307
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7298
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7317
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7309
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7317
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7317
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7317
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7332
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7312
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7324
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7311
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7328
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7324
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7324
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7333
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7336
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7340
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7332
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7332
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7336
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7339
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7339
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7327
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7332
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7335
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7336
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7346
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7344
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7335
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7340
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7343
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7350
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7343
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7350
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7346
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7346
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7343
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7342
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7335
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7347
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7342
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7345

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [42]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5562 - accuracy: 0.7314 - 396ms/epoch - 1ms/step
Loss: 0.5561932325363159, Accuracy: 0.7314285635948181

In [43]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data

model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)
# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5539 - accuracy: 0.7328 - 470ms/epoch - 2ms/step
Loss: 0.5539474487304688, Accuracy: 0.7328279614448547

In [44]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy= nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# YOUR CODE HERE

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5607 - accuracy: 0.7319 - 447ms/epoch - 2ms/step
Loss: 0.560730516910553, Accuracy: 0.7318950295448303

### Step 3: Save each of your alternative models as an HDF5 file.

In [45]:
# Set the file path for the first alternative model
# YOUR CODE HERE
file_path =  "/Users/matt/Desktop/BootCamp/Starter_Code_13/Resources/AlphabetSoup_A1.H5"




# Export your model to a HDF5 file
# YOUR CODE HERE
nn_A1.save(file_path)

In [46]:
# Set the file path for the second alternative model
file_path = "/Users/matt/Desktop/BootCamp/Starter_Code_13/Resources/AlphabetSoup_A2.H5"
# YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE
nn_A2.save(file_path)